max_planning_retries: 15
planner_patience: 30
number_of_recovery_behaviors: 10
planner_frequency: 10
controller_frequency: 10
allow_unknown: false
controller_patience: 10.0
oscillation_timeout: 10.0
oscillation_distance: 0.2
recovery_behaviors:
  - name: conservative_reset
    type: clear_costmap_recovery/ClearCostmapRecovery

conservative_reset:
  reset_distance: 5
